CATEGORIES = [
    "Mechanics",
    "Fluid Dynamics",
    "Waves & Acoustics",
    "Thermodynamics",
    "Electromagnetism",
    "Optics",
    "Quantum & Modern",
    "Other",
]

CATEGORY_COLORS = {
    "Mechanics":        "#5b8dee",
    "Fluid Dynamics":   "#00b894",
    "Waves & Acoustics":"#fd79a8",
    "Thermodynamics":   "#e17055",
    "Electromagnetism": "#a29bfe",
    "Optics":           "#fdcb6e",
    "Quantum & Modern": "#00cec9",
    "Other":            "#636e72",
}

PROBLEMS: dict[tuple[int, int], dict] = {
    # ── 2017 ──
    # NOTE: YAML resultdump is empty for 2017; only team-level fight HTML pages exist.
    # Individual participant performance data for 2017 is unavailable — these entries
    # are present so the category map is complete if data is added later.
    (2017,  1): {"name": "Invent Yourself",           "category": "Other"},
    (2017,  2): {"name": "Balloon Airhorn",            "category": "Waves & Acoustics"},
    (2017,  3): {"name": "Single Lens Telescope",      "category": "Optics"},
    (2017,  4): {"name": "Magnetic Hills",             "category": "Electromagnetism"},
    (2017,  5): {"name": "Leidenfrost Stars",          "category": "Thermodynamics"},
    (2017,  6): {"name": "Fast Chain",                 "category": "Mechanics"},
    (2017,  7): {"name": "Spiral Waves",               "category": "Fluid Dynamics"},
    (2017,  8): {"name": "Visualising Density",        "category": "Optics"},
    (2017,  9): {"name": "Ball in a Tube",             "category": "Mechanics"},
    (2017, 10): {"name": "Pulling Glasses Apart",      "category": "Mechanics"},
    (2017, 11): {"name": "Hair Hygrometer",            "category": "Thermodynamics"},
    (2017, 12): {"name": "Torsion Gyroscope",          "category": "Mechanics"},
    (2017, 13): {"name": "Resonating Glass",           "category": "Waves & Acoustics"},
    (2017, 14): {"name": "Gee-Haw Whammy Diddle",     "category": "Mechanics"},
    (2017, 15): {"name": "Boiled Egg",                 "category": "Thermodynamics"},
    (2017, 16): {"name": "Metronome Synchronization",  "category": "Mechanics"},
    (2017, 17): {"name": "Vacuum Bazooka",             "category": "Mechanics"},
    # ── 2018 ──
    (2018,  1): {"name": "Invent Yourself",            "category": "Other"},
    (2018,  2): {"name": "Colour of Powders",          "category": "Optics"},
    (2018,  3): {"name": "Dancing Coin",               "category": "Thermodynamics"},
    (2018,  4): {"name": "Heron's Fountain",           "category": "Fluid Dynamics"},
    (2018,  5): {"name": "Drinking Straw",             "category": "Fluid Dynamics"},
    (2018,  6): {"name": "Ring Oiler",                 "category": "Fluid Dynamics"},
    (2018,  7): {"name": "Conical Piles",              "category": "Mechanics"},
    (2018,  8): {"name": "Cusps in a Cylinder",        "category": "Fluid Dynamics"},
    (2018,  9): {"name": "Candle in Water",            "category": "Thermodynamics"},
    (2018, 10): {"name": "Tesla Valve",                "category": "Fluid Dynamics"},
    (2018, 11): {"name": "Azimuthal-Radial Pendulum",  "category": "Mechanics"},
    (2018, 12): {"name": "Curie Point Engine",         "category": "Electromagnetism"},
    (2018, 13): {"name": "Weighing Time",              "category": "Mechanics"},
    (2018, 14): {"name": "Radiant Lantern",            "category": "Thermodynamics"},
    (2018, 15): {"name": "Blowing Bubbles",            "category": "Fluid Dynamics"},
    (2018, 16): {"name": "Acoustic Levitation",        "category": "Waves & Acoustics"},
    (2018, 17): {"name": "Water Bottle",               "category": "Fluid Dynamics"},
    # ── 2019 ──
    (2019,  1): {"name": "Invent Yourself",            "category": "Other"},
    (2019,  2): {"name": "Aerosol",                    "category": "Fluid Dynamics"},
    (2019,  3): {"name": "Undertone Sound",            "category": "Waves & Acoustics"},
    (2019,  4): {"name": "Funnel and Ball",            "category": "Fluid Dynamics"},
    (2019,  5): {"name": "Filling Up a Bottle",        "category": "Fluid Dynamics"},
    (2019,  6): {"name": "Hurricane Balls",            "category": "Mechanics"},
    (2019,  7): {"name": "Loud Voice",                 "category": "Waves & Acoustics"},
    (2019,  8): {"name": "Sci-Fi Sound",               "category": "Waves & Acoustics"},
    (2019,  9): {"name": "Soy Sauce Optics",           "category": "Optics"},
    (2019, 10): {"name": "Suspended Water Wheel",      "category": "Fluid Dynamics"},
    (2019, 11): {"name": "Flat Self-Assembly",         "category": "Fluid Dynamics"},
    (2019, 12): {"name": "Gyroscope Teslameter",       "category": "Electromagnetism"},
    (2019, 13): {"name": "Moiré Thread Counter",       "category": "Optics"},
    (2019, 14): {"name": "Looping Pendulum",           "category": "Mechanics"},
    (2019, 15): {"name": "Newton's Cradle",            "category": "Mechanics"},
    (2019, 16): {"name": "Sinking Bubbles",            "category": "Fluid Dynamics"},
    (2019, 17): {"name": "Popsicle Chain Reaction",    "category": "Mechanics"},
    # ── 2022 ──
    (2022,  1): {"name": "Invent Yourself",          "category": "Other"},
    (2022,  2): {"name": "Rayleigh Disk",             "category": "Waves & Acoustics"},
    (2022,  3): {"name": "Ring on the Rod",           "category": "Mechanics"},
    (2022,  4): {"name": "Unsinkable Disk",           "category": "Fluid Dynamics"},
    (2022,  5): {"name": "Bimetallic Oscillator",     "category": "Thermodynamics"},
    (2022,  6): {"name": "Tennis Ball Tower",         "category": "Mechanics"},
    (2022,  7): {"name": "Three-Sided Dice",          "category": "Mechanics"},
    (2022,  8): {"name": "Equipotential Lines",       "category": "Electromagnetism"},
    (2022,  9): {"name": "Water Spiral",              "category": "Fluid Dynamics"},
    (2022, 10): {"name": "Droplet Explosion",         "category": "Fluid Dynamics"},
    (2022, 11): {"name": "Balls on an Elastic Band",  "category": "Mechanics"},
    (2022, 12): {"name": "Strange Motion",            "category": "Mechanics"},
    (2022, 13): {"name": "Candle Powered Turbine",    "category": "Thermodynamics"},
    (2022, 14): {"name": "Ball on Membrane",          "category": "Mechanics"},
    (2022, 15): {"name": "Boycott Effect",            "category": "Fluid Dynamics"},
    (2022, 16): {"name": "Saving Honey",              "category": "Fluid Dynamics"},
    (2022, 17): {"name": "Invisibility",              "category": "Optics"},
    # ── 2023 ──
    (2023,  1): {"name": "Fractal Fingers",                 "category": "Fluid Dynamics"},
    (2023,  2): {"name": "Oscillating Sphere",              "category": "Mechanics"},
    (2023,  3): {"name": "Siren",                           "category": "Waves & Acoustics"},
    (2023,  4): {"name": "Coloured Line",                   "category": "Optics"},
    (2023,  5): {"name": "Whistling Mesh",                  "category": "Waves & Acoustics"},
    (2023,  6): {"name": "Magnetic-Mechanical Oscillator",  "category": "Electromagnetism"},
    (2023,  7): {"name": "Faraday Waves",                   "category": "Fluid Dynamics"},
    (2023,  8): {"name": "Euler's Pendulum",                "category": "Mechanics"},
    (2023,  9): {"name": "Oscillating Screw",               "category": "Mechanics"},
    (2023, 10): {"name": "Upstream Flow",                   "category": "Fluid Dynamics"},
    (2023, 11): {"name": "Ball on Ferrite Rod",             "category": "Electromagnetism"},
    (2023, 12): {"name": "Rice Kettlebells",                "category": "Mechanics"},
    (2023, 13): {"name": "Ponyo's Heat Tube",               "category": "Thermodynamics"},
    (2023, 14): {"name": "Jet Refraction",                  "category": "Fluid Dynamics"},
    (2023, 15): {"name": "Pancake Rotation",                "category": "Mechanics"},
    (2023, 16): {"name": "Thermoacoustic Engine",           "category": "Thermodynamics"},
    (2023, 17): {"name": "Arrester Bed",                    "category": "Mechanics"},
    # ── 2024 ──
    (2024,  1): {"name": "Invent Yourself",             "category": "Other"},
    (2024,  2): {"name": "Droplet Microscope",          "category": "Optics"},
    (2024,  3): {"name": "Rigid Ramp Walker",           "category": "Mechanics"},
    (2024,  4): {"name": "Shooting Rubber Band",        "category": "Mechanics"},
    (2024,  5): {"name": "Ping Pong Rocket",            "category": "Fluid Dynamics"},
    (2024,  6): {"name": "Non-contact Resistance",      "category": "Electromagnetism"},
    (2024,  7): {"name": "Giant Sounding Plate",        "category": "Waves & Acoustics"},
    (2024,  8): {"name": "Another Magnetic Levitation", "category": "Electromagnetism"},
    (2024,  9): {"name": "Juicy Solar Cell",            "category": "Quantum & Modern"},
    (2024, 10): {"name": "Magnetic Gear",               "category": "Electromagnetism"},
    (2024, 11): {"name": "Pumping Straw",               "category": "Fluid Dynamics"},
    (2024, 12): {"name": "The Soap Spiral",             "category": "Fluid Dynamics"},
    (2024, 13): {"name": "Charge Meter",                "category": "Electromagnetism"},
    (2024, 14): {"name": "Ruler Trick",                 "category": "Mechanics"},
    (2024, 15): {"name": "Wet Scroll",                  "category": "Fluid Dynamics"},
    (2024, 16): {"name": "Cushion Catapult",            "category": "Mechanics"},
    (2024, 17): {"name": "Quantum Light Dimmer",        "category": "Quantum & Modern"},
    # ── 2025 ──
    (2025,  1): {"name": "Paper Boomerang",              "category": "Mechanics"},
    (2025,  2): {"name": "Air Muscle",                   "category": "Mechanics"},
    (2025,  3): {"name": "Lato Lato",                    "category": "Mechanics"},
    (2025,  4): {"name": "Climbing Magnets",             "category": "Electromagnetism"},
    (2025,  5): {"name": "Dancing Slinky",               "category": "Mechanics"},
    (2025,  6): {"name": "Dripping Faucet",              "category": "Fluid Dynamics"},
    (2025,  7): {"name": "Ruler Cannon",                 "category": "Mechanics"},
    (2025,  8): {"name": "Levitating Fluid",             "category": "Fluid Dynamics"},
    (2025,  9): {"name": "Magnetic Assist",              "category": "Electromagnetism"},
    (2025, 10): {"name": "Rayleigh-Benard Convection",   "category": "Fluid Dynamics"},
    (2025, 11): {"name": "Spring Hysteresis",            "category": "Mechanics"},
    (2025, 12): {"name": "Sound Versus Fire",            "category": "Waves & Acoustics"},
    (2025, 13): {"name": "Spaghetti Accelerator",        "category": "Mechanics"},
    (2025, 14): {"name": "Water Bottle Rocket",          "category": "Fluid Dynamics"},
    (2025, 15): {"name": "Wailing Bowl",                 "category": "Waves & Acoustics"},
    (2025, 16): {"name": "Wirtz Pump",                   "category": "Fluid Dynamics"},
    (2025, 17): {"name": "Quantum Fingerprint",          "category": "Quantum & Modern"},
}
